POST http://127.0.0.1:5000/api/auth/login
Content-Type: application/json;charset=UTF-8

{
  "email": "o.davies@pbgdigital.co.uk",
  "password": "admin"
}


###
POST http://127.0.0.1:5000/api/pages/bobf0adrmtimm42kpos0
Content-Type: application/json;charset=UTF-8

{
    "attributes": {
      "header": {
        "image": {}
      },
      "content": {
        "List": [
          {
            "email": "info@pbgcare.co.uk",
            "title": "Head Office",
            "mobile": "01322686765",
            "address": "130 Old Street, London EC1V 9BD"
          }
        ]
      }
    },
    "name": "Contact",
    "route": "contact",
    "uuid": "bobf0adrmtimm42kpos0"
  }
  
